name: Compilar servidores com MSVS
# build_servers_msbuild.yml

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    paths:
      # Sempre acionar todas as GitHub Actions se uma action ou algo relacionado ao CI foi alterado
      - '.github/workflows/**'
      - 'tools/ci/**'
      # Este workflow deve rodar quando um arquivo em um diretório de código fonte foi modificado.
      - 'src/**'
      - '3rdparty/**'

jobs:
  build:
    # GitHub Actions verifica por '[ci skip]', '[skip ci]', '[no ci]', '[skip actions]', ou '[actions skip]' mas não versões hifenizadas.
    # É um catch-all caso um Pull Request tenha sido aberto e alguém esteja no piloto automático.
    if: "!contains(github.event.head_commit.message, 'ci-skip')"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          # A label windows-latest atualmente aponta para windows-2019.
          # Disponível: windows-2016, windows-2019 e windows-2022
          os: [windows-latest]
          # Executamos verificações de compilação tanto para Renewal quanto para PRE-Renewal
          mode: ['PRE', 'RE']

    steps:
      - uses: actions/checkout@v4

      - name: Adicionar msbuild ao PATH
        uses: microsoft/setup-msbuild@v2

      - name: Compilar solução em Debug
        if: ${{ matrix.mode == 'PRE' }}
        run: msbuild rAthena.sln -t:rebuild -property:Configuration=Debug /p:DefineConstants="BUILDBOT%3BPRERE" /warnaserror

      - name: Compilar solução em Debug
        if: ${{ matrix.mode == 'RE' }}
        run: msbuild rAthena.sln -t:rebuild -property:Configuration=Debug /p:DefineConstants="BUILDBOT" /warnaserror