name: Compilar servidores em modo VIP
# build_servers_vip.yml

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    paths:
      # Sempre acionar todas as GitHub Actions se uma action ou algo relacionado ao CI foi alterado
      - '.github/workflows/**'
      - 'tools/ci/**'
      # Este workflow deve rodar quando um arquivo em um diretório de código fonte foi modificado.
      - 'src/**'
      - '3rdparty/**'

jobs:
  build:
    # GitHub Actions verifica por '[ci skip]', '[skip ci]', '[no ci]', '[skip actions]', ou '[actions skip]' mas não versões hifenizadas.
    # É um catch-all caso um Pull Request tenha sido aberto e alguém esteja no piloto automático.
    if: "!contains(github.event.head_commit.message, 'ci-skip')"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          # A label ubuntu-latest atualmente aponta para ubuntu-24.04.
          # Disponível: ubuntu-24.04, ubuntu-22.04
          os: [ubuntu-latest]
          # Versões mais antigas do GCC não estão disponíveis via listas de repositórios aptitude não alteradas.
          gcc: ['11']
          # Executamos verificações de compilação tanto para Renewal quanto para PRE-Renewal
          mode: ['PRE', 'RE']

    steps:
      - uses: actions/checkout@v4

      # Um simples 'yes' e 'no' pode ser confuso, então usamos nomes para exibir no job atual e depois os convertemos para uso no compilador.
      - name: Parse de Variáveis - PRE
        if: ${{ matrix.mode == 'PRE' }} 
        run: |
          echo "PRERE=yes" >> $GITHUB_ENV
      - name: Parse de Variáveis - RE
        if: ${{ matrix.mode == 'RE' }} 
        run: |
          echo "PRERE=no" >> $GITHUB_ENV

      - name: Atualizar & Instalar pacotes
        # Os runners do Ubuntu já possuem a maioria dos pacotes que o rAthena requer para compilar.
        # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md
        run: |
          sudo apt update
          sudo apt install zlib1g-dev libpcre3-dev gcc-${{ matrix.gcc }} g++-${{ matrix.gcc }}

      - name: Iniciar MySQL
        run: sudo systemctl start mysql.service

      - name: Configurar Banco de Dados e importar dados da tabela
        run: ./tools/ci/sql.sh

      - name: Comando - configure
        env:
            CONFIGURE_FLAGS: 'CC=gcc-${{ matrix.gcc }} CXX=g++-${{ matrix.gcc }} --enable-prere=${{ env.PRERE }} --enable-buildbot=yes --enable-vip=yes'
        run: ./configure $CONFIGURE_FLAGS
      
      - name: Comando - make clean
        run: make clean

      - name: Comando - make server
        run: make server

      - name: Executar Uma Vez - login-server
        run: ./login-server --run-once

      - name: Executar Uma Vez - char-server
        run: ./char-server --run-once

      - name: Executar Uma Vez - map-server
        run: ./map-server --run-once