name: Compilar servidores com Clang no macOS
# build_servers_cmake_osx.yml

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    paths:
      # Sempre acionar todas as GitHub Actions se uma action ou algo relacionado ao CI foi alterado
      - '.github/workflows/**'
      - 'tools/ci/**'
      # Este workflow deve rodar quando um arquivo em um diretório de código fonte foi modificado.
      - 'src/**'
      - '3rdparty/**'
      # Este workflow deve rodar sempre que um arquivo relacionado ao CMake foi modificado
      - '**/CMakeLists.txt'

jobs:
  build:
    # GitHub Actions verifica por '[ci skip]', '[skip ci]', '[no ci]', '[skip actions]', ou '[actions skip]' mas não versões hifenizadas.
    # É um catch-all caso um Pull Request tenha sido aberto e alguém esteja no piloto automático.
    if: "!contains(github.event.head_commit.message, 'ci-skip')"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          # A label macos-latest atualmente aponta para macos-14.
          # A label YAML macos-latest usará macos-15 em Agosto de 2025
          os: [macos-14, macos-15]

    steps:
      - uses: actions/checkout@v4

      - name: Atualizar & Instalar pacotes
        # Os runners do macOS já possuem a maioria dos pacotes que o rAthena requer para compilar.
        # https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md
        # https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md
        run: |
          brew update
          brew install pcre
          brew install mysql
          brew install mysql-client

      # Instalar CMake mais recente.
      - uses: lukka/get-cmake@latest

      - name: Criar diretório de compilação
        run: mkdir cbuild

      - name: Criar Unix Makefiles
        run: |
          cd cbuild
          cmake ..

      - name: Comando - make
        run: |
          cd cbuild
          make