name: Compilar servidores com GCC
# build_servers_gcc.yml

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    paths:
      # Sempre acionar todas as GitHub Actions se uma action ou algo relacionado ao CI foi alterado
      - '.github/workflows/**'
      - 'tools/ci/**'
      # Este workflow deve rodar quando um arquivo em um diretório de código fonte foi modificado.
      - 'src/**'
      - '3rdparty/**'

jobs:
  build:
    # GitHub Actions verifica por '[ci skip]', '[skip ci]', '[no ci]', '[skip actions]', ou '[actions skip]' mas não versões hifenizadas.
    # É um catch-all caso um Pull Request tenha sido aberto e alguém esteja no piloto automático.
    if: "!contains(github.event.head_commit.message, 'ci-skip')"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          # A label ubuntu-latest atualmente aponta para ubuntu-24.04.
          # Disponível: ubuntu-24.04, ubuntu-22.04
          os: [ubuntu-latest]
          # Versões mais antigas do GCC não estão disponíveis via listas de repositórios aptitude não alteradas.
          gcc: ['9', '10', '11', '12']
          # GCC 13 foi removido do 22.04, incluí-lo como um job separado
          include:
            - os: ubuntu-24.04
              gcc: 13

    steps:
      - uses: actions/checkout@v4

      - name: Atualizar & Instalar pacotes
        # Os runners do Ubuntu já possuem a maioria dos pacotes que o rAthena requer para compilar.
        # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md
        run: |
          sudo apt update
          sudo apt install zlib1g-dev libpcre3-dev gcc-${{ matrix.gcc }} g++-${{ matrix.gcc }}

      - name: Comando - configure
        env:
            CONFIGURE_FLAGS: 'CC=gcc-${{ matrix.gcc }} CXX=g++-${{ matrix.gcc }}'
        # -Werror: para tratar todos os warnings como erros
        # -Wno-error=builtin-declaration-mismatch: caso contrário as verificações do ./configure falham
        run: ./configure $CONFIGURE_FLAGS --enable-buildbot=yes CXXFLAGS='-Werror -Wno-error=builtin-declaration-mismatch'
      
      - name: Comando - make clean
        run: make clean

      - name: Comando - make all
        run: make all